language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
install:
  - pip install pipenv
  - pipenv install --dev --system

jobs:
  include:
    - stage: check
      script: flake8 --ignore E501 pytidy
    - stage: check
      script: flake8 --ignore E501 tests
    - stage: check
      script: mypy pytidy

script: pytest --cov=pytidy

after_success:
  - coveralls

before_deploy:
  - git config --local user.name "taxpon"
  - git config --local user.email "taxpon@gmail.com"
  - export RELEASE_TAG=$(bash scripts/get_version.sh)
  - git tag $RELEASE_TAG

deploy:
  - provider: pypi
    user: ${PYPI_USERNAME}
    password: ${PYPI_PASSWORD}
    distributions: "sdist bdist_wheel"
    on:
      branch: master

after_deploy:
  - git checkout develop
  - bash scripts/update_version.sh
  - git commit -a -m "Update version"
  - git push origin develop
  - git push origin --tags

stages:
  - check
  - test
  - name: deploy
    if: branch = master AND type != pull_request

notifications:
  email: false